/**
 * Signal-validation gate for docs/plans/galaxy-communities.md, Direction B. Read that plan first.
 *
 * Question this answers: does `songs.embedding` (generated by `generateSongContext` from the plain
 * "Title" by Artist string, gemini-embedding-001, 768-dim — the SAME embedding buildPickEmbedding uses
 * for mood-based matching) actually separate songs by musical scene/genre, or does it just reproduce
 * mood/artist/title semantics? If it's the latter, Direction B must switch to MusicBrainz genre/tag data
 * instead of clustering this embedding.
 *
 * Deliberately varied, hand-picked evaluation set — NOT the live seed catalog (27 picks across 7 people
 * is too small and too correlated with a handful of personas' taste to validate anything; the plan is
 * explicit that eyeballing clusters at that scale only validates the seed choices). Each song below is
 * tagged with an expected genre bucket. For each song we compute its nearest neighbors under the real
 * production embedding, and report what fraction of top-3 neighbors share the expected bucket — plus the
 * raw MusicBrainz genre/tags and Gemini mood summary for a human to actually read, not just the score.
 *
 * This script is throwaway/diagnostic per the plan — it writes nothing to the database and adds no
 * schema. Run it, read the report, and make the signal decision by hand:
 *
 *   node --env-file=.env.local node_modules/.bin/tsx scripts/evaluate-song-scene-signal.ts
 */
import { generateSongContext } from "../lib/gemini/generateSongContext";
import { resolveSong } from "../lib/musicbrainz/client";

const MIN_GEMINI_INTERVAL_MS = 4500;

/** Deliberately varied: 8 genre buckets, 3 songs each, chosen to be unambiguous to a human listener. */
const EVAL_SET: { title: string; artist: string; bucket: string }[] = [
  { title: "Kerala", artist: "Bonobo", bucket: "electronic" },
  { title: "Archangel", artist: "Burial", bucket: "electronic" },
  { title: "Emerald Rush", artist: "Jon Hopkins", bucket: "electronic" },

  { title: "Only Shallow", artist: "My Bloody Valentine", bucket: "shoegaze" },
  { title: "Alison", artist: "Slowdive", bucket: "shoegaze" },
  { title: "Just Like Honey", artist: "The Jesus and Mary Chain", bucket: "shoegaze" },

  { title: "Mykonos", artist: "Fleet Foxes", bucket: "folk" },
  { title: "Skinny Love", artist: "Bon Iver", bucket: "folk" },
  { title: "The Cave", artist: "Mumford & Sons", bucket: "folk" },

  { title: "Holiday in Cambodia", artist: "Dead Kennedys", bucket: "punk" },
  { title: "London Calling", artist: "The Clash", bucket: "punk" },
  { title: "Blitzkrieg Bop", artist: "Ramones", bucket: "punk" },

  { title: "Clair de Lune", artist: "Claude Debussy", bucket: "classical" },
  { title: "Moonlight Sonata", artist: "Ludwig van Beethoven", bucket: "classical" },
  { title: "Gymnopedie No. 1", artist: "Erik Satie", bucket: "classical" },

  { title: "HUMBLE.", artist: "Kendrick Lamar", bucket: "hiphop" },
  { title: "Sicko Mode", artist: "Travis Scott", bucket: "hiphop" },
  { title: "N.Y. State of Mind", artist: "Nas", bucket: "hiphop" },

  { title: "Master of Puppets", artist: "Metallica", bucket: "metal" },
  { title: "Raining Blood", artist: "Slayer", bucket: "metal" },
  { title: "Paranoid", artist: "Black Sabbath", bucket: "metal" },

  { title: "Untitled (How Does It Feel)", artist: "D'Angelo", bucket: "soul" },
  { title: "Ivy", artist: "Frank Ocean", bucket: "soul" },
  { title: "Adorn", artist: "Miguel", bucket: "soul" },
];

function cosine(a: number[], b: number[]): number {
  let dot = 0;
  let na = 0;
  let nb = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    na += a[i] * a[i];
    nb += b[i] * b[i];
  }
  return dot / (Math.sqrt(na) * Math.sqrt(nb));
}

type Evaluated = {
  title: string;
  artist: string;
  bucket: string;
  embedding: number[];
  contextSummary: string;
  mbTags: string[];
};

async function fetchGenreTags(title: string, artist: string): Promise<string[]> {
  try {
    const resolution = await resolveSong(title, artist);
    if (!resolution) return [];
    const res = await fetch(`https://musicbrainz.org/ws/2/recording/${resolution.mbid}?inc=tags+genres&fmt=json`, {
      headers: { "User-Agent": `SongGalaxy/0.1 (hackgt-meta-track; contact: ${process.env.MUSICBRAINZ_CONTACT_EMAIL})` },
    });
    if (!res.ok) return [];
    const data = (await res.json()) as { tags?: { name: string }[]; genres?: { name: string }[] };
    const names = [...(data.genres ?? []), ...(data.tags ?? [])].map((t) => t.name);
    return [...new Set(names)];
  } catch (err) {
    console.warn(`  (MusicBrainz lookup failed for "${title}" by ${artist}: ${err instanceof Error ? err.message : err})`);
    return [];
  }
}

async function main() {
  console.log(`Evaluating ${EVAL_SET.length} songs across ${new Set(EVAL_SET.map((s) => s.bucket)).size} genre buckets.\n`);

  const evaluated: Evaluated[] = [];
  for (const song of EVAL_SET) {
    const started = Date.now();
    const [context, mbTags] = await Promise.all([
      generateSongContext(song.title, song.artist),
      fetchGenreTags(song.title, song.artist), // internally throttled to 1 req/sec by resolveSong
    ]);
    evaluated.push({ ...song, embedding: context.embedding, contextSummary: context.contextSummary, mbTags });
    console.log(`  embedded: "${song.title}" by ${song.artist} [${song.bucket}]`);
    const wait = MIN_GEMINI_INTERVAL_MS - (Date.now() - started);
    if (wait > 0) await new Promise((r) => setTimeout(r, wait));
  }

  console.log("\n" + "=".repeat(100));
  console.log("REPORT — read this by hand. Does 'top-3 neighbors' actually share a sound, or just a mood/vibe?");
  console.log("=".repeat(100));

  let totalAgreement = 0;
  for (const song of evaluated) {
    const ranked = evaluated
      .filter((o) => o !== song)
      .map((o) => ({ o, sim: cosine(song.embedding, o.embedding) }))
      .sort((a, b) => b.sim - a.sim)
      .slice(0, 3);
    const agreement = ranked.filter((r) => r.o.bucket === song.bucket).length;
    totalAgreement += agreement / 3;

    console.log(`\n"${song.title}" by ${song.artist}  [expected: ${song.bucket}]`);
    console.log(`  Gemini mood: ${song.contextSummary}`);
    console.log(`  MusicBrainz tags/genres: ${song.mbTags.length ? song.mbTags.join(", ") : "(none returned)"}`);
    console.log(`  Top-3 embedding neighbors (bucket-agreement ${agreement}/3):`);
    for (const { o, sim } of ranked) {
      console.log(`    ${sim.toFixed(3)}  "${o.title}" by ${o.artist}  [${o.bucket}]${o.bucket === song.bucket ? "  <- same bucket" : ""}`);
    }
  }

  const rate = totalAgreement / evaluated.length;
  console.log("\n" + "=".repeat(100));
  console.log(`Genre-agreement rate across the eval set: ${(rate * 100).toFixed(0)}%`);
  console.log("Read this as a rough signal, not a verdict — the actual gate is: do the neighbor lists above");
  console.log("look like shared sound to a human, or shared mood/artist-recognition/title semantics?");
  console.log("If they look like the latter, switch Direction B's signal to MusicBrainz genre/tag data.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
